### ISSUE TITLE
unable to validate entity when submitted key is missing

### ISSUE THREAD

**Issue by videni** [videni/SimpleRestBundle#1]
Validation
```
App\Bundle\serBundle\Entity\User:
    constraints:
      - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:  { groups: ['acme'], fields: ['username'], message: 'username is taken'}
    properties:
        username:
           - NotBlank: { groups: ['create'] }

```

FormType
```
class UserType extends AbstractResourceType
{
     /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options);

        $builder
            ->add('username', Type\TextType::class, [
                'label'         => 'app_user.user.username.label',
            ])
            ->add('plainPassword', Type\PasswordType::class, [
                'label' => 'app_user.user.plain_password.label'
            ])
        ;
    }
}
```
Test
```
     /**
     * @test
     */
    public function it_is_not_allows_to_create_device_user_without_username()
    {
        $data =
<<<EOT
        {
            "plain_password": "123456"
        }
EOT;

        $this->client->request(
           'POST',
            '/api/admin/user/create',
            [],
            [],
            $this->getAuthorizedHeaderWithContentType(),
            $data
        );

        $response = $this->client->getResponse();

        $this->assertResponseCode($response, Response::HTTP_BAD_REQUEST);
    }
```

this test will fail, somehow Symfony doesn't validate the username.
